# Generated by Django 3.2.20 on 2023-08-22 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signoffs_signets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=100)),
                ('article_text', models.TextField(max_length=1000)),
                ('publication_status', models.CharField(choices=[('not_requested', 'Publication Not Requested'), ('pending', 'Publication Pending'), ('approved', 'Published')], default='not_requested', max_length=25)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=250)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RevokedNewsletterSignet',
            fields=[
                ('revokedsignet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='signoffs_signets.revokedsignet')),
            ],
            options={
                'abstract': False,
            },
            bases=('signoffs_signets.revokedsignet',),
        ),
        migrations.CreateModel(
            name='PublicationRequestSignet',
            fields=[
                ('signet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='signoffs_signets.signet')),
                ('article', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pub_request_signatories', to='article.article')),
            ],
            options={
                'ordering': ['timestamp'],
                'abstract': False,
            },
            bases=('signoffs_signets.signet',),
        ),
        migrations.CreateModel(
            name='PublicationApprovalSignet',
            fields=[
                ('signet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='signoffs_signets.signet')),
                ('article', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='pub_approve_signatories', to='article.article')),
            ],
            options={
                'ordering': ['timestamp'],
                'abstract': False,
            },
            bases=('signoffs_signets.signet',),
        ),
        migrations.CreateModel(
            name='ArticleSignet',
            fields=[
                ('signet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='signoffs_signets.signet')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_signatories', to='article.article')),
            ],
            options={
                'ordering': ['timestamp'],
                'abstract': False,
            },
            bases=('signoffs_signets.signet',),
        ),
        migrations.CreateModel(
            name='CommentSignet',
            fields=[
                ('signet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='signoffs_signets.signet')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_signet', to='article.comment', unique=True)),
            ],
            options={
                'ordering': ['timestamp'],
                'abstract': False,
            },
            bases=('signoffs_signets.signet',),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_approval_signet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='article.publicationapprovalsignet'),
        ),
        migrations.AddField(
            model_name='article',
            name='publication_request_signet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='article.publicationrequestsignet'),
        ),
    ]
