# Generated by Django 3.2.20 on 2023-08-22 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signoffs_signets', '0001_initial'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_approval_signet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='signoffs_signets.signet'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_request_signet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='signoffs_signets.signet'),
        ),
        migrations.AlterField(
            model_name='articlesignet',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatories', to='article.article'),
        ),
    ]
