# Generated by Django 3.2.20 on 2023-07-29 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20230729_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='agreement_signet',
            new_name='publish_signet',
        ),
    ]
