# Generated by Django 3.2.20 on 2023-08-08 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('details', models.TextField(max_length=1000)),
                ('assigned_to', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_assigned_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
