# Generated by Django 3.2.20 on 2023-08-08 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signoffs_approvals', '0001_initial'),
        ('editor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approval_stamp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='signoffs_approvals.stamp'),
        ),
    ]
