# Generated by Django 3.2.20 on 2023-08-10 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signoffs_approvals', '0001_initial'),
        ('editor_app', '0003_alter_project_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProjectSignet',
            fields=[
                ('signet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='signoffs_approvals.signet')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_project_signet', to='editor_app.project')),
            ],
            options={
                'ordering': ['timestamp'],
                'abstract': False,
            },
            bases=('signoffs_approvals.signet',),
        ),
    ]
