# Generated by Django 3.2.20 on 2023-08-10 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('signoffs_approvals', '0001_initial'),
        ('editor_app', '0005_auto_20230810_2024'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewProjectSignet',
            new_name='AssignmentSignet',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
