# Generated by Django 3.2.20 on 2023-08-11 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signoffs_approvals', '0001_initial'),
        ('editor_app', '0006_auto_20230810_2217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignmentSignet',
        ),
    ]
