# Generated by Django 3.2.20 on 2023-08-15 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor_app', '0007_delete_assignmentsignet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assigned_by',
        ),
    ]
